name: Linter

on:
    push:
      branches:
        - Rohit

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest

    steps:
        - name: Checkout repository
          uses: actions/checkout@v2
          with:
            fetch-depth: 0

        - name: Lint Code Base
          uses: actions/checkout@v2
          env:
            VALIDATE_ALL_CODEBASE: false
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

